import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/AddPlants.module.sass'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import SearchBar from './components/SearchBar/SearchBar'
import Plant from './components/Plant/Plant'
import Link from 'next/link'
import TobysButton from './components/TobysButton/TobysButton'
import { useState } from 'react'

const AddPlants: NextPage = () => {
    const test2 = ["Plant A", "Plant B", "Plant C", "Plant D", "Plant E", "Plant F"]
    const [plantImage, setPlantImage] = useState('')

    function submit() {
    console.log("this is a test")
    }

  

    return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header></Header>
        <main className={styles.main}>
        
            <div className={styles.AddPlantsHeaderTitleContainer}>
                <h1>ADD PLANTS</h1>    
            </div>
            <div className={styles.AddPlantsInputsContainers}>
                <div className={styles.AddPlantsImageContainer}>
                    <h1>+</h1>
                    {/* <Image src={plantImage} alt='Plant Image'></Image> */}
                </div>
                <div className={styles.AddPlantsNameContainer}>
                    <input placeholder='Name'></input>
                </div>
                <div className={styles.AddPlantsDescriptionContainer}>
                    <textarea placeholder='Descritpion'></textarea>
                </div>
                <div className={styles.AddPlantsButtonContainer}>
                    <TobysButton name="Done" path="MyPlants" delegate={submit}></TobysButton>
                </div>
            </div>
            

        </main>
        <Footer></Footer>
    </div>
    )
}

export default AddPlants
