import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import Plant from './components/Plant/Plant'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Home!
        </h1>

        <Plant></Plant>

      </main>
      <Footer></Footer>
    </div>
  )
}

export default Home
