import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@styles/PlantFinder.module.sass'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import SearchBar from './components/SearchBar/SearchBar'
import PlantComponent from './components/Plant/Plant'
import { ToolController } from '@/backEnd/dataAccessLayer/actions/tool'
import { Tool } from '@/shared/interfaces/Tool'
import { useState } from 'react'

interface ToolProps {
  tools: [Tool]
}

const PlantsCare: NextPage = (props: ToolProps) => {
    const [tools, setTools] = useState(props.tools)
    return (
        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header></Header>
            <main className={styles.main}>
            <SearchBar></SearchBar>

            <h1>Plants Care</h1>
            
            <div className={styles.PlantFinderResultsContainer}>
            {
                tools.map(
                (item) => {
                    return (
                        <div className={styles.PlantFinderResult} key={ String(item) }>
                            <PlantComponent name={item.name} description={item.description} imagePath={`/tools/${item.imagePath}`}></PlantComponent>
                        </div>
                    );
                }
                )
            }
            </div>

            </main>
            <Footer></Footer>
        </div>
    )
}

// get server side props using id value passed by link in list card
export async function getServerSideProps() {
    // get all lists associated with the given id
    const queryResult = await ToolController.getTools();
    // parse the results into an array of SSLists
    const tools = JSON.parse(JSON.stringify(queryResult)) as [ToolController];
    return {
        props: {
        tools
        }
    };
}

export default PlantsCare
