import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/PlantFinder.module.sass'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import SearchBar from './components/SearchBar/SearchBar'
import PlantComponent from './components/Plant/Plant'
import { PlantController } from '@/backEnd/dataAccessLayer/actions/plant';
import { Plant } from '@/shared/interfaces/Plant';
import { useState } from 'react'

interface PlantProps {
    plants: [Plant]
}

const PlantsFinder: NextPage = (props: PlantProps) => {
const [plants, setPlants] = useState(props.plants)

  return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header></Header>
        <main className={styles.main}>
        <SearchBar></SearchBar>

        <h1>Plants Finder</h1>
        
        <div className={styles.PlantFinderResultsContainer}>
        {
        plants.map(
            (item) => {
                return (
                    <div className={styles.PlantFinderResult} key={ String(item) }>
                        <PlantComponent name={item.name} description={item.description} imagePath={`/plants/${item.imagePath}`}></PlantComponent>
                    </div>
                );
            }
        )
        }
        </div>

        </main>
        <Footer></Footer>
    </div>
  )
}

// get server side props using id value passed by link in list card
export async function getServerSideProps() {
    // get all lists associated with the given id
    const queryResult = await PlantController.getPlants();
    // parse the results into an array of SSLists
    const plants = JSON.parse(JSON.stringify(queryResult)) as [PlantController];
    return {
        props: {
        plants
        }
    };
}

export default PlantsFinder
