import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/PlantFinder.module.sass';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import PlantComponent from './components/Plant/Plant';
import { PlantController } from '@/backEnd/dataAccessLayer/actions/plant';
import { Plant } from '@/shared/interfaces/Plant';
import { useState } from 'react';
import stylesSearch from '@styles/SearchBar.module.sass';
import searchIcon from '@public/searchIcon.png';
import {SearchPlants} from '@/shared/actions/search';

const PlantsFinder: NextPage = (props: {plants: [Plant?]}) => {
    // plants retrieved
    const [plants, setPlants] = useState(props.plants);
    // the value used to search for plants
    const [searchVal, setSearchVal] = useState("");

    // the task to perform our search for plants
    async function search(event) {
        // the result of our search for plants
        const result:[PlantController?] = await SearchPlants(event, searchVal) as [PlantController?];

        // sets plants depending on result
        if (result == null) {
            setPlants(props.plants);
        }
        else {
            setPlants(result);
        }
    }

    return (
        <div className={styles.container}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header></Header>
            <main className={styles.main}>
                <div className={stylesSearch.SearchBarContainer}>
                    <div>
                        <div className={stylesSearch.SearchBarIcon}><Image src={searchIcon} alt="me" layout="fill" objectFit="contain" /></div>
                        <input className={stylesSearch.SearchBar} onChange = {e => { setSearchVal(e.currentTarget.value);}} placeholder='search' type="text" name='search' onKeyDown={search} />
                    </div>
                </div>
                <h1>PLANTS FINDER</h1>
                <div className={styles.PlantFinderResultsContainer}>
                {
                plants.map(
                    (item) => {
                        return (
                            <div className={styles.PlantFinderResult} key={ String(item.name) }>
                                <PlantComponent name={item.name} description={item.description} imagePath={`/plants/${item.imagePath}`}></PlantComponent>
                            </div>
                        );
                    }
                )
                }
                </div>
            </main>
            <Footer></Footer>
        </div>
    );
};

export async function getServerSideProps() {
    // get all plants
    const queryResult = await PlantController.getPlants();
    // parse the results into an array of plants and returns them
    const plants = JSON.parse(JSON.stringify(queryResult)) as [PlantController];
    
    return {
        props: {
        plants
        }
    };
}

export default PlantsFinder;
