import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/LogUp.module.sass'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import SearchBar from './components/SearchBar/SearchBar'
import Plant from './components/Plant/Plant'
import Link from 'next/link'
import TobysButton from './components/TobysButton/TobysButton'
import PlantWithEdit from './components/PlantWithEdit/PlantWithEdit'
import plantdeco from '../../public/signupdeco.png'

const SingUp: NextPage = () => {
  const test2 = ["Plant A", "Plant B", "Plant C", "Plant D", "Plant E", "Plant F"]

  function test() {
    console.log("this is a test")
  }

  return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header></Header>
        <div className={styles.plantDeco}><Image src={plantdeco} alt="me" layout="fill" objectFit="contain" /></div>
        <main className={styles.main}>
            <div className={styles.LogUpTitleContainer}>
                <h1>SIGN UP</h1>    
            </div>
            <div className={styles.inputContainer}>
                <input placeholder='Email'></input>
            </div>
            <div className={styles.inputContainer}>
                <input placeholder='Confirm Email'></input>
            </div>
            <div className={styles.inputContainer}>
                <input placeholder='Password'></input>
            </div>
            <div className={styles.inputContainer}>
                <input placeholder='Confirm Password'></input>
            </div>
            <div className={styles.LogUpButtonContainer}>
                <TobysButton name="Sign Up" path="MyPlants"></TobysButton>
            </div>
        </main>
        <Footer></Footer>
    </div>
  )
}

export default SingUp